### ISSUE TITLE
Unable to bypass Mullvad DNS via DNS override option in Passepartout

### ISSUE THREAD

**Issue by seanob86** [passepartoutvpn/api-source-mullvad#1]
I just signed up with Mullvad as my current NordVPN subscription is coming to an end.
By using the NordVPN provider based option in app I can successfully connect and override/bypass Nord's DNS by providing my own preferred DNS server.

However with Mullvad I am unable to bypass their DNS servers as per the above method within the passepartout app. I can verify by dnsleaktest.com

I am trying to override the DNS to my AdGuard Home server (which works with Nord), but you can test with google 8.8.8.8 and Mullvad and verifying on dnsleaktest.com

If I unmask the network data and view the debug log I can see a dozen lines below 'starting tunnel' the following 'DNS: ["8.8.8.8"].

Debug log attached
[debug-20190701-120206.txt](https://github.com/passepartoutvpn/passepartout-ios/files/3343808/debug-20190701-120206.txt)

**Comment by keeshux** [comment]
Thanks for the report. I've just added a new preset for those endpoints.

Do this in Passepartout from the Mullvad profile:

- "Refresh infrastructure"
- Preset > "Custom DNS"
- Endpoint > Pick any of the two, "Automatic" defaults to UDP first

Let me know if DNS works this way.

**Comment by seanob86** [comment]
Thank you for the quick fix 👍
I confirmed that custom DNS works as per your instructions after refreshing infrastructure for both UDP and TCP

Awesome that the app doesn’t require an update to make this work 😄

**Comment by keeshux** [comment]
Nice! To be honest, I would have never realized the underlying issue without your insight. :)

**Comment by keeshux** [comment]
Also eligible for a FAQ: https://passepartoutvpn.app/faq/#mullvad-ignores-my-custom-dns-settings

**Comment by seanob86** [comment]
Hi @keeshux! Wasn't sure if I should open a new issue but for context I will raise it here for now.

The custom DNS works great after applying it after updating the infrastructure. But after reboot of my iPhone the custom DNS preset no longer appears as an option. It basically reverts to how it was previously prior to when you asked me to do the infrastructure update. 

To workaround I just need to update the infrastructure again - but I need to remember this after reboot.

**Comment by keeshux** [comment]
Bummer. Follow up in https://github.com/passepartoutvpn/passepartout-ios/issues/54
