### ISSUE TITLE
Missing endpoints for Mullvad

### ISSUE THREAD

**Issue by superDuperCyberTechno** [passepartoutvpn/api-source-mullvad#4]
It seems that the amount of endpoints for Mullvad is very much incomplete...

Can this be resolved programatically? Is the list hardcoded?

**Comment by keeshux** [comment]
FYI here are the Ruby scripts generating the Mullvad endpoints for Passepartout on a daily basis.

**Comment by superDuperCyberTechno** [comment]
Alright, so I think I maybe got a little ahead of myself. It seems that you pick the server right after you select country. I thought one would select server in the provider menu under "Endpoint" but that only provides the IP and hostname for the currently selected server.
